version: "3"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  book-service:
    build: .
    image: book-service
    ports:
      - "8082:8082"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: book-service.access
        fluentd-async-connect: "true"
    depends_on:
      - fluentd

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.2.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  prometheus:
    image: prom/prometheus:latest
    ports:
     - 9090:9090