version: "3"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  book-service:
    build: .
    image: book-service
    ports:
      - "8082:8082"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: book-service.access
        fluentd-async-connect: "true"
    depends_on:
      - fluentd

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.2.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  prometheus:
    image: prom/prometheus:latest
    ports:
     - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    #volumes:
    #  - ./grafana:/var/lib/grafana
    #env_file:
    #  - ./grafana/config.monitoring
    depends_on:
      - prometheus
    restart: always

    jaeger:
      image: jaegertracing/all-in-one:latest
        ports:
          - "5775:5775/udp"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "16686:16686"
          - "14268:14268"
          - "9411:9411"